# Generated by Django 3.0.1 on 2019-12-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nazwa lokalu')),
                ('slug', models.SlugField(blank=True, max_length=300, verbose_name='Link')),
                ('img', models.ImageField(max_length=300, upload_to='Place/static/locals/img', verbose_name='Zdjęcie')),
                ('address', models.CharField(max_length=500, verbose_name='Adres')),
                ('number_phone', models.CharField(max_length=26, verbose_name='Numer telefonu')),
                ('hours', models.TextField(max_length=2000, verbose_name='Godziny otwarcia')),
                ('news', models.TextField(default='', max_length=2000, verbose_name='Aktualności')),
                ('maps', models.CharField(default='', max_length=1000, verbose_name='Mapa')),
                ('description', models.TextField(default='', max_length=3000, verbose_name='Opis i Informacje')),
                ('status', models.BooleanField(default=False, verbose_name='Opublikuj')),
            ],
            options={
                'verbose_name': 'Lokal',
                'verbose_name_plural': 'Lokale',
            },
        ),
    ]
