# Generated by Django 3.0.1 on 2019-12-29 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, default='', max_length=3000, verbose_name='Opis i Informacje'),
        ),
        migrations.AlterField(
            model_name='place',
            name='maps',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Mapa'),
        ),
        migrations.AlterField(
            model_name='place',
            name='news',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='Aktualności'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(blank=True, max_length=200, verbose_name='Nazwa Potrawy')),
                ('dish_components', models.CharField(blank=True, default='', max_length=1200, verbose_name='Składniki')),
                ('dish_category', models.CharField(choices=[('Pizza', 'Pizza'), ('Kebab', 'Kebab'), ('Zestaw Obiadowy', 'Zestaw Obiadowy'), ('Zapiekanki', 'Zapiekanki'), ('Zupy', 'Zupy'), ('Burgery', 'Burgery'), ('Kanapki', 'Kanapki'), ('Salatki', 'Sałatki'), ('Surowki', 'Surówki'), ('Desery', 'Desery'), ('Napoje zimne', 'Napoje zimne'), ('Napoje ciepłe', 'Napoje ciepłe'), ('Inne', 'Inne')], default='Kategoria', max_length=200, verbose_name='Kategoria')),
                ('pizza_price', models.CharField(blank=True, default='', help_text='np.Mała-10zł', max_length=300, verbose_name='Rozmiar i cena Pizzy')),
                ('price', models.DecimalField(decimal_places=2, default='00', max_digits=5, verbose_name='Cena')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place', to='restaurants.Place')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
    ]
