# Generated by Django 2.1 on 2019-05-27 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(blank=True, max_length=200, verbose_name='Nazwa Potrawy')),
                ('dish_components', models.CharField(blank=True, default='', max_length=1200, verbose_name='Składniki')),
                ('dish_category', models.CharField(choices=[('Pizza', 'Pizza'), ('Kebab', 'Kebab'), ('Burgery', 'Burgery'), ('Kanapki', 'Kanapki'), ('Sałatki', 'Sałatki'), ('Napoje', 'Napoje'), ('Inne', 'Inne')], default='Kategoria', max_length=200, verbose_name='Kategoria')),
                ('pizza_price', models.CharField(blank=True, default='', help_text='np.Mała-10zł', max_length=300, verbose_name='Rozmiar i cena Pizzy')),
                ('price', models.DecimalField(decimal_places=2, default='00', max_digits=5, verbose_name='Cena')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa lokalu')),
                ('slug', models.SlugField(default='', max_length=300, verbose_name='Link')),
                ('img', models.ImageField(blank=True, max_length=500, upload_to='Place/static/locals/img', verbose_name='Zdjęcie Lokalu')),
                ('address', models.CharField(max_length=1000, verbose_name='Adres')),
                ('number_phone', models.CharField(max_length=26, verbose_name='Numer telefonu')),
                ('hours', models.TextField(max_length=2000, verbose_name='Godziny otwarcia')),
                ('news', models.TextField(blank=True, default='', max_length=2000, verbose_name='Aktualności')),
                ('maps', models.CharField(blank=True, default='', max_length=1000, verbose_name='Mapa')),
                ('status', models.BooleanField(default=False, verbose_name='Opublikuj')),
            ],
            options={
                'verbose_name': 'Lokal',
                'verbose_name_plural': 'Lokale',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place', to='place.Place'),
        ),
    ]
