# Generated by Django 2.1.7 on 2019-05-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Opublikuj'),
        ),
    ]
