# Generated by Django 2.1 on 2019-06-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20190601_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, default='', max_length=3000, verbose_name='Opis i Informacje'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dish_category',
            field=models.CharField(choices=[('Pizza', 'Pizza'), ('Kebab', 'Kebab'), ('Burgery', 'Burgery'), ('Kanapki', 'Kanapki'), ('Sałatki', 'Sałatki'), ('Napoje', 'Napoje'), ('Inne', 'Inne'), ('rozmiar i cenna', 'rozmiar i cenna'), ('zestaw obiadowy', 'zestaw obiadowy'), ('zapiekanki', 'zapiekanki')], default='Kategoria', max_length=200, verbose_name='Kategoria'),
        ),
    ]
