# Generated by Django 2.1.7 on 2019-05-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20190525_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='maps',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Mapa'),
        ),
        migrations.AlterField(
            model_name='place',
            name='news',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='Aktualności'),
        ),
    ]
